#!/usr/bin/env python3

# Little MUS Player v0.3
# 
# Copyright 2025 Andrew Towers
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


# This script generates the att_lfo table.


# MIDI modulation (CC1) is used to control LFO intensity in MUS,
# for example in E1M8 "Sign Of Evil".
# MIDI controller values are in the range 0-127, although modulation
# intensity tends to be low, e.g. 0-25 in E1M8.

# We need a sine wave at 6 Hz for the LFO.
# At 140 ticks per second, that's 140/6 = 23.333 ticks per cycle.
# So we'll calculate a table of 23 attenuation values in the shape
# of a sine-wave, and adjust the playing note's attenuation each tick.

# We also need to handle intensity, the whole point of modulation.
# Since the LFO table is so small, and to avoid multiplies etc,
# we'll calculate 8 LFO tables at different intensities, one per four
# modulation-controller steps.


import math

cycleSteps = 12
numTables = 8
amplitude = 2

rows = []
for intensity in range(amplitude,(numTables+1)*amplitude,amplitude):
    table = []
    for n in range(0,cycleSteps):
        sample = intensity * math.sin(n * 2*math.pi / cycleSteps)
        table.append(int(sample))
    rows.append(",".join(map(str,table)))

print("// GENERATED by lfo.py")
print(f"static int8_t lfo_table[12*8] = {{\n    {",\n    ".join(rows)}\n}};\n")
